### ISSUE TITLE
Engine gets stuck in FRESH Status when new episode is started / NoSuchFieldError

### ISSUE THREAD

**Issue by rlistle** [t-wolfeadam/Alpyne#18]
Hello,
i´m currently trying to develop a warehouse simulation model with reinforcement learning via Alpyne.
I´ve created a simple BaseAlpyneEnv class and a training method with PPO like in the rlpolicy_train.py from the StockManagmentGame example. 
During the learning the PPO algorithm resets the model run at the end of an episode by sending the configuration to the model. But instead of starting the next run properly and get into RUNNING state again, the server gets stuck in the wait_for_completion method as the server constantly returns the FRESH state after the configuration was send. The log file looks as following:

<img width="833" alt="StuckInFRESHStatus" src="https://user-images.githubusercontent.com/28153357/168476570-5453bbbd-cd29-4c41-931e-280966a09e41.png">

I found a post on stack overflow where someone identified the ressource block from the process modeling library as the cause of this issue. I removed the ressource block in my simulation and the reset works like it should. 

So i tried to replace this legacy block with the corresponding block from the material handling library (transport fleet). Following from this i also had to replace the rack system with storage system. With that i wasn't even able to start the first episode as i got the following NoSuchFieldError: 

<img width="884" alt="NoSuchFieldError" src="https://user-images.githubusercontent.com/28153357/168474013-559a1d37-7934-4516-8e1c-a7692d0cb9b1.png">

So for some reason the import of the RackPlacement enum is missing in Alpyne, as the simulation works well in AnyLogic.

Is this issue known or is there any workaround so that i can use the ressource block or the storage system as intended? 
Any help would be appreciated as i´d like to use Alpyne for my university research :)

Best regards
Rebecca

**Comment by t-wolfeadam** [comment]
Are you able to send the link from SO? Because it's very weird that resource pools would cause that (it's also definitely not a legacy block, though maybe you're thinking of the storage element from the PML).

Regarding the `RACK_PLACEMENT_STAND_ALONE` error, that may be due to Alpyne not being updated for the latest version of AnyLogic. As a workaround, navigate to where the library files are located for the alpyne server (`site-packages\alpyne\resources\alpyne_lib`) and replace `com.anylogic.engine.jar` with the file from your AnyLogic installation (`AnyLogic 8.7 <EDITION>\plugins\com.anylogic.engine_8.7.12.202205231048\com.anylogic.engine.jar`)

**Comment by rlistle** [comment]
Sorry, what you mean by "SO"? 

Thanks for that hint, now I'm able to use the new storage block, but unfortunately i'm also getting the fresh error now with that setup, doesnt matter if i'm using it in combination with the ressource or the transporter fleet block...

**Comment by simonsnow2017** [comment]
I met the same problem, the model stuck in the wait_for_completion() in reset()

**Comment by t-wolfeadam** [comment]
Closing as this is likely resolved in v1.0.0. Feel free to create a new issue if it remains.
